/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package collage;

import com.mysql.cj.xdevapi.Table;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Adinath Pawar
 */
public class Cource extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cource.class.getName());
    private Object con;

    /**
     * Creates new form BCAI
     */
    public Cource() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" BCA I Students");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(255, 51, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BCA I");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Table.setBackground(new java.awt.Color(255, 255, 255));
        Table.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Table.setForeground(new java.awt.Color(0, 51, 51));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Roll number", "Name", "Class", "yearofclass", "semester", "department", "mobile_no", "date_of_birth", "address", "blood_group", "gender"
            }
        ));
        jScrollPane1.setViewportView(Table);

        jButton2.setBackground(new java.awt.Color(255, 51, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("BCA II");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 51, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BCA III");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 51, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("BCS I");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 51, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("BCS II");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 51, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("BCS III");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 51, 0));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("BSC I");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 51, 0));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("BSC II");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 51, 0));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("BSC III");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(255, 51, 0));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("BA I");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(255, 51, 0));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("BA II");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(255, 51, 0));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("BA III");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(255, 51, 0));
        jButton13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("MCA I");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(255, 51, 0));
        jButton14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("MCA II");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(255, 51, 0));
        jButton15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("MCA III");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(255, 51, 0));
        jButton16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("MSC I");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(255, 51, 0));
        jButton17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setText("MSC II");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(255, 51, 0));
        jButton18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("MSC III");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1247, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10)
                    .addComponent(jButton11)
                    .addComponent(jButton12))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton13)
                    .addComponent(jButton14)
                    .addComponent(jButton15))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton18)
                    .addComponent(jButton17)
                    .addComponent(jButton16))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(jButton7)
                    .addComponent(jButton10)
                    .addComponent(jButton13)
                    .addComponent(jButton16))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton5)
                    .addComponent(jButton8)
                    .addComponent(jButton11)
                    .addComponent(jButton14)
                    .addComponent(jButton17))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton6)
                    .addComponent(jButton9)
                    .addComponent(jButton12)
                    .addComponent(jButton15)
                    .addComponent(jButton18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // Assuming you have a JTable named jTable1
            try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/collage", "root", "system");

    String sql = "SELECT * FROM student WHERE Class='BCA' AND yearofclass=1";
    PreparedStatement pstmt = con.prepareStatement(sql);
    ResultSet rs = pstmt.executeQuery();

    DefaultTableModel model = (DefaultTableModel) Table.getModel();
    model.setRowCount(0);  // Clear existing rows
    boolean hasResult=false;

    while (rs.next()) {
        hasResult = true;
        String studentRollnumber = String.valueOf(rs.getInt("Rollnumber"));
        String studentName = rs.getString("StudentName");
        String className = rs.getString("Class");
        String yearofcls=rs.getString("yearofclass");
        String sem=rs.getString("semester");
        String deapart=rs.getString("department");
        String Mobileno=rs.getString("mobile_no");
        String datebirth=rs.getString("date_of_birth");
        String addr=rs.getString("address");
        String bgroup=rs.getString("blood_group");
        String genderr=rs.getString("gender");

        String[] row = {studentRollnumber, studentName, className,yearofcls,sem,deapart,Mobileno,datebirth,addr,bgroup,genderr};
        model.addRow(row);
    }
        if(!hasResult){
            JOptionPane.showMessageDialog(this, "No Any Student Of BCA I");
        }

    con.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}

 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here
         try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/collage", "root", "system");

    String sql = "SELECT * FROM student WHERE Class='BCA' AND yearofclass=2";
    PreparedStatement pstmt = con.prepareStatement(sql);
    ResultSet rs = pstmt.executeQuery();

    DefaultTableModel model = (DefaultTableModel) Table.getModel();
    model.setRowCount(0);  // Clear existing rows
    boolean hasResult=false;
    

    while (rs.next()) {
        hasResult =true;
        String studentRollnumber = String.valueOf(rs.getInt("Rollnumber"));
        String studentName = rs.getString("StudentName");
        String className = rs.getString("Class");
        String yearofcls=rs.getString("yearofclass");
        String sem=rs.getString("semester");
        String deapart=rs.getString("department");
        String Mobileno=rs.getString("mobile_no");
        String datebirth=rs.getString("date_of_birth");
        String addr=rs.getString("address");
        String bgroup=rs.getString("blood_group");
        String genderr=rs.getString("gender");

        String[] row = {studentRollnumber, studentName, className,yearofcls,sem,deapart,Mobileno,datebirth,addr,bgroup,genderr};
        model.addRow(row);
        
    }
    if(!hasResult){
            JOptionPane.showMessageDialog(this, "No Any Students Of BCA II");
            
        }

    con.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
            try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/collage", "root", "system");

    String sql = "SELECT * FROM student WHERE Class='BCA' AND yearofclass=3";
    PreparedStatement pstmt = con.prepareStatement(sql);
    ResultSet rs = pstmt.executeQuery();

    DefaultTableModel model = (DefaultTableModel) Table.getModel();
    model.setRowCount(0);  // Clear existing rows
    boolean hasResult=false;
    

    while (rs.next()) {
        hasResult =true;
        String studentRollnumber = String.valueOf(rs.getInt("Rollnumber"));
        String studentName = rs.getString("StudentName");
        String className = rs.getString("Class");
        String yearofcls=rs.getString("yearofclass");
        String sem=rs.getString("semester");
        String deapart=rs.getString("department");
        String Mobileno=rs.getString("mobile_no");
        String datebirth=rs.getString("date_of_birth");
        String addr=rs.getString("address");
        String bgroup=rs.getString("blood_group");
        String genderr=rs.getString("gender");

        String[] row = {studentRollnumber, studentName, className,yearofcls,sem,deapart,Mobileno,datebirth,addr,bgroup,genderr};
        model.addRow(row);
        
    }
    if(!hasResult){
            JOptionPane.showMessageDialog(this, "No Any Students Of BCA III");
            
        }

    con.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
        
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
              try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/collage", "root", "system");

    String sql = "SELECT * FROM student WHERE Class='BCS' AND yearofclass=1";
    PreparedStatement pstmt = con.prepareStatement(sql);
    ResultSet rs = pstmt.executeQuery();

    DefaultTableModel model = (DefaultTableModel) Table.getModel();
    model.setRowCount(0);  // Clear existing rows
    boolean hasResult=false;
    

    while (rs.next()) {
        hasResult =true;
        String studentRollnumber = String.valueOf(rs.getInt("Rollnumber"));
        String studentName = rs.getString("StudentName");
        String className = rs.getString("Class");
        String yearofcls=rs.getString("yearofclass");
        String sem=rs.getString("semester");
        String deapart=rs.getString("department");
        String Mobileno=rs.getString("mobile_no");
        String datebirth=rs.getString("date_of_birth");
        String addr=rs.getString("address");
        String bgroup=rs.getString("blood_group");
        String genderr=rs.getString("gender");

        String[] row = {studentRollnumber, studentName, className,yearofcls,sem,deapart,Mobileno,datebirth,addr,bgroup,genderr};
        model.addRow(row);
        
    }
    if(!hasResult){
            JOptionPane.showMessageDialog(this, "No Any Students Of BCS I");
            
        }

    con.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
              try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/collage", "root", "system");

    String sql = "SELECT * FROM student WHERE Class='BCS' AND yearofclass=2";
    PreparedStatement pstmt = con.prepareStatement(sql);
    ResultSet rs = pstmt.executeQuery();

    DefaultTableModel model = (DefaultTableModel) Table.getModel();
    model.setRowCount(0);  // Clear existing rows
    boolean hasResult=false;
    

    while (rs.next()) {
        hasResult =true;
        String studentRollnumber = String.valueOf(rs.getInt("Rollnumber"));
        String studentName = rs.getString("StudentName");
        String className = rs.getString("Class");
        String yearofcls=rs.getString("yearofclass");
        String sem=rs.getString("semester");
        String deapart=rs.getString("department");
        String Mobileno=rs.getString("mobile_no");
        String datebirth=rs.getString("date_of_birth");
        String addr=rs.getString("address");
        String bgroup=rs.getString("blood_group");
        String genderr=rs.getString("gender");

        String[] row = {studentRollnumber, studentName, className,yearofcls,sem,deapart,Mobileno,datebirth,addr,bgroup,genderr};
        model.addRow(row);
        
    }
    if(!hasResult){
            JOptionPane.showMessageDialog(this, "No Any Students Of BCS II");
            
        }

    con.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
              try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/collage", "root", "system");

    String sql = "SELECT * FROM student WHERE Class='BCS' AND yearofclass=3";
    PreparedStatement pstmt = con.prepareStatement(sql);
    ResultSet rs = pstmt.executeQuery();

    DefaultTableModel model = (DefaultTableModel) Table.getModel();
    model.setRowCount(0);  // Clear existing rows
    boolean hasResult=false;
    

    while (rs.next()) {
        hasResult =true;
        String studentRollnumber = String.valueOf(rs.getInt("Rollnumber"));
        String studentName = rs.getString("StudentName");
        String className = rs.getString("Class");
        String yearofcls=rs.getString("yearofclass");
        String sem=rs.getString("semester");
        String deapart=rs.getString("department");
        String Mobileno=rs.getString("mobile_no");
        String datebirth=rs.getString("date_of_birth");
        String addr=rs.getString("address");
        String bgroup=rs.getString("blood_group");
        String genderr=rs.getString("gender");

        String[] row = {studentRollnumber, studentName, className,yearofcls,sem,deapart,Mobileno,datebirth,addr,bgroup,genderr};
        model.addRow(row);
        
    }
    if(!hasResult){
            JOptionPane.showMessageDialog(this, "No Any Students Of BCS III");
            
        }

    con.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
                try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/collage", "root", "system");

    String sql = "SELECT * FROM student WHERE Class='BSC' AND yearofclass=1";
    PreparedStatement pstmt = con.prepareStatement(sql);
    ResultSet rs = pstmt.executeQuery();

    DefaultTableModel model = (DefaultTableModel) Table.getModel();
    model.setRowCount(0);  // Clear existing rows
    boolean hasResult=false;
    

    while (rs.next()) {
        hasResult =true;
        String studentRollnumber = String.valueOf(rs.getInt("Rollnumber"));
        String studentName = rs.getString("StudentName");
        String className = rs.getString("Class");
        String yearofcls=rs.getString("yearofclass");
        String sem=rs.getString("semester");
        String deapart=rs.getString("department");
        String Mobileno=rs.getString("mobile_no");
        String datebirth=rs.getString("date_of_birth");
        String addr=rs.getString("address");
        String bgroup=rs.getString("blood_group");
        String genderr=rs.getString("gender");

        String[] row = {studentRollnumber, studentName, className,yearofcls,sem,deapart,Mobileno,datebirth,addr,bgroup,genderr};
        model.addRow(row);
        
    }
    if(!hasResult){
            JOptionPane.showMessageDialog(this, "No Any Students Of BSC I");
            
        }

    con.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
                try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/collage", "root", "system");

    String sql = "SELECT * FROM student WHERE Class='BSC' AND yearofclass=2";
    PreparedStatement pstmt = con.prepareStatement(sql);
    ResultSet rs = pstmt.executeQuery();

    DefaultTableModel model = (DefaultTableModel) Table.getModel();
    model.setRowCount(0);  // Clear existing rows
    boolean hasResult=false;
    

    while (rs.next()) {
        hasResult =true;
        String studentRollnumber = String.valueOf(rs.getInt("Rollnumber"));
        String studentName = rs.getString("StudentName");
        String className = rs.getString("Class");
        String yearofcls=rs.getString("yearofclass");
        String sem=rs.getString("semester");
        String deapart=rs.getString("department");
        String Mobileno=rs.getString("mobile_no");
        String datebirth=rs.getString("date_of_birth");
        String addr=rs.getString("address");
        String bgroup=rs.getString("blood_group");
        String genderr=rs.getString("gender");

        String[] row = {studentRollnumber, studentName, className,yearofcls,sem,deapart,Mobileno,datebirth,addr,bgroup,genderr};
        model.addRow(row);
        
    }
    if(!hasResult){
            JOptionPane.showMessageDialog(this, "No Any Students Of BSC II");
            
        }

    con.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
                try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/collage", "root", "system");

    String sql = "SELECT * FROM student WHERE Class='BSC' AND yearofclass=3";
    PreparedStatement pstmt = con.prepareStatement(sql);
    ResultSet rs = pstmt.executeQuery();

    DefaultTableModel model = (DefaultTableModel) Table.getModel();
    model.setRowCount(0);  // Clear existing rows
    boolean hasResult=false;
    

    while (rs.next()) {
        hasResult =true;
        String studentRollnumber = String.valueOf(rs.getInt("Rollnumber"));
        String studentName = rs.getString("StudentName");
        String className = rs.getString("Class");
        String yearofcls=rs.getString("yearofclass");
        String sem=rs.getString("semester");
        String deapart=rs.getString("department");
        String Mobileno=rs.getString("mobile_no");
        String datebirth=rs.getString("date_of_birth");
        String addr=rs.getString("address");
        String bgroup=rs.getString("blood_group");
        String genderr=rs.getString("gender");

        String[] row = {studentRollnumber, studentName, className,yearofcls,sem,deapart,Mobileno,datebirth,addr,bgroup,genderr};
        model.addRow(row);
        
    }
    if(!hasResult){
            JOptionPane.showMessageDialog(this, "No Any Students Of BSC III");
            
        }

    con.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
                try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/collage", "root", "system");

    String sql = "SELECT * FROM student WHERE Class='BA' AND yearofclass=1";
    PreparedStatement pstmt = con.prepareStatement(sql);
    ResultSet rs = pstmt.executeQuery();

    DefaultTableModel model = (DefaultTableModel) Table.getModel();
    model.setRowCount(0);  // Clear existing rows
    boolean hasResult=false;
    

    while (rs.next()) {
        hasResult =true;
        String studentRollnumber = String.valueOf(rs.getInt("Rollnumber"));
        String studentName = rs.getString("StudentName");
        String className = rs.getString("Class");
        String yearofcls=rs.getString("yearofclass");
        String sem=rs.getString("semester");
        String deapart=rs.getString("department");
        String Mobileno=rs.getString("mobile_no");
        String datebirth=rs.getString("date_of_birth");
        String addr=rs.getString("address");
        String bgroup=rs.getString("blood_group");
        String genderr=rs.getString("gender");

        String[] row = {studentRollnumber, studentName, className,yearofcls,sem,deapart,Mobileno,datebirth,addr,bgroup,genderr};
        model.addRow(row);
        
    }
    if(!hasResult){
            JOptionPane.showMessageDialog(this, "No Any Students Of BA I");
            
        }

    con.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
                try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/collage", "root", "system");

    String sql = "SELECT * FROM student WHERE Class='BA' AND yearofclass=2";
    PreparedStatement pstmt = con.prepareStatement(sql);
    ResultSet rs = pstmt.executeQuery();

    DefaultTableModel model = (DefaultTableModel) Table.getModel();
    model.setRowCount(0);  // Clear existing rows
    boolean hasResult=false;
    

    while (rs.next()) {
        hasResult =true;
        String studentRollnumber = String.valueOf(rs.getInt("Rollnumber"));
        String studentName = rs.getString("StudentName");
        String className = rs.getString("Class");
        String yearofcls=rs.getString("yearofclass");
        String sem=rs.getString("semester");
        String deapart=rs.getString("department");
        String Mobileno=rs.getString("mobile_no");
        String datebirth=rs.getString("date_of_birth");
        String addr=rs.getString("address");
        String bgroup=rs.getString("blood_group");
        String genderr=rs.getString("gender");

        String[] row = {studentRollnumber, studentName, className,yearofcls,sem,deapart,Mobileno,datebirth,addr,bgroup,genderr};
        model.addRow(row);
        
    }
    if(!hasResult){
            JOptionPane.showMessageDialog(this, "No Any Students Of BA II");
            
        }

    con.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
                try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/collage", "root", "system");

    String sql = "SELECT * FROM student WHERE Class='BA' AND yearofclass=3";
    PreparedStatement pstmt = con.prepareStatement(sql);
    ResultSet rs = pstmt.executeQuery();

    DefaultTableModel model = (DefaultTableModel) Table.getModel();
    model.setRowCount(0);  // Clear existing rows
    boolean hasResult=false;
    

    while (rs.next()) {
        hasResult =true;
        String studentRollnumber = String.valueOf(rs.getInt("Rollnumber"));
        String studentName = rs.getString("StudentName");
        String className = rs.getString("Class");
        String yearofcls=rs.getString("yearofclass");
        String sem=rs.getString("semester");
        String deapart=rs.getString("department");
        String Mobileno=rs.getString("mobile_no");
        String datebirth=rs.getString("date_of_birth");
        String addr=rs.getString("address");
        String bgroup=rs.getString("blood_group");
        String genderr=rs.getString("gender");

        String[] row = {studentRollnumber, studentName, className,yearofcls,sem,deapart,Mobileno,datebirth,addr,bgroup,genderr};
        model.addRow(row);
        
    }
    if(!hasResult){
            JOptionPane.showMessageDialog(this, "No Any Students Of BA III");
            
        }

    con.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
                try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/collage", "root", "system");

    String sql = "SELECT * FROM student WHERE Class='MCA' AND yearofclass=1";
    PreparedStatement pstmt = con.prepareStatement(sql);
    ResultSet rs = pstmt.executeQuery();

    DefaultTableModel model = (DefaultTableModel) Table.getModel();
    model.setRowCount(0);  // Clear existing rows
    boolean hasResult=false;
    

    while (rs.next()) {
        hasResult =true;
        String studentRollnumber = String.valueOf(rs.getInt("Rollnumber"));
        String studentName = rs.getString("StudentName");
        String className = rs.getString("Class");
        String yearofcls=rs.getString("yearofclass");
        String sem=rs.getString("semester");
        String deapart=rs.getString("department");
        String Mobileno=rs.getString("mobile_no");
        String datebirth=rs.getString("date_of_birth");
        String addr=rs.getString("address");
        String bgroup=rs.getString("blood_group");
        String genderr=rs.getString("gender");

        String[] row = {studentRollnumber, studentName, className,yearofcls,sem,deapart,Mobileno,datebirth,addr,bgroup,genderr};
        model.addRow(row);
        
    }
    if(!hasResult){
            JOptionPane.showMessageDialog(this, "No Any Students Of MCA I");
            
        }

    con.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
                try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/collage", "root", "system");

    String sql = "SELECT * FROM student WHERE Class='MCA' AND yearofclass=2";
    PreparedStatement pstmt = con.prepareStatement(sql);
    ResultSet rs = pstmt.executeQuery();

    DefaultTableModel model = (DefaultTableModel) Table.getModel();
    model.setRowCount(0);  // Clear existing rows
    boolean hasResult=false;
    

    while (rs.next()) {
        hasResult =true;
        String studentRollnumber = String.valueOf(rs.getInt("Rollnumber"));
        String studentName = rs.getString("StudentName");
        String className = rs.getString("Class");
        String yearofcls=rs.getString("yearofclass");
        String sem=rs.getString("semester");
        String deapart=rs.getString("department");
        String Mobileno=rs.getString("mobile_no");
        String datebirth=rs.getString("date_of_birth");
        String addr=rs.getString("address");
        String bgroup=rs.getString("blood_group");
        String genderr=rs.getString("gender");

        String[] row = {studentRollnumber, studentName, className,yearofcls,sem,deapart,Mobileno,datebirth,addr,bgroup,genderr};
        model.addRow(row);
        
    }
    if(!hasResult){
            JOptionPane.showMessageDialog(this, "No Any Students Of MCA II");
            
        }

    con.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
        
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
                try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/collage", "root", "system");

    String sql = "SELECT * FROM student WHERE Class='MCA' AND yearofclass=3";
    PreparedStatement pstmt = con.prepareStatement(sql);
    ResultSet rs = pstmt.executeQuery();

    DefaultTableModel model = (DefaultTableModel) Table.getModel();
    model.setRowCount(0);  // Clear existing rows
    boolean hasResult=false;
    

    while (rs.next()) {
        hasResult =true;
        String studentRollnumber = String.valueOf(rs.getInt("Rollnumber"));
        String studentName = rs.getString("StudentName");
        String className = rs.getString("Class");
        String yearofcls=rs.getString("yearofclass");
        String sem=rs.getString("semester");
        String deapart=rs.getString("department");
        String Mobileno=rs.getString("mobile_no");
        String datebirth=rs.getString("date_of_birth");
        String addr=rs.getString("address");
        String bgroup=rs.getString("blood_group");
        String genderr=rs.getString("gender");

        String[] row = {studentRollnumber, studentName, className,yearofcls,sem,deapart,Mobileno,datebirth,addr,bgroup,genderr};
        model.addRow(row);
        
    }
    if(!hasResult){
            JOptionPane.showMessageDialog(this, "No Any Students Of MCA III");
            
        }

    con.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
        
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
                try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/collage", "root", "system");

    String sql = "SELECT * FROM student WHERE Class='MSC' AND yearofclass=1";
    PreparedStatement pstmt = con.prepareStatement(sql);
    ResultSet rs = pstmt.executeQuery();

    DefaultTableModel model = (DefaultTableModel) Table.getModel();
    model.setRowCount(0);  // Clear existing rows
    boolean hasResult=false;
    

    while (rs.next()) {
        hasResult =true;
        String studentRollnumber = String.valueOf(rs.getInt("Rollnumber"));
        String studentName = rs.getString("StudentName");
        String className = rs.getString("Class");
        String yearofcls=rs.getString("yearofclass");
        String sem=rs.getString("semester");
        String deapart=rs.getString("department");
        String Mobileno=rs.getString("mobile_no");
        String datebirth=rs.getString("date_of_birth");
        String addr=rs.getString("address");
        String bgroup=rs.getString("blood_group");
        String genderr=rs.getString("gender");

        String[] row = {studentRollnumber, studentName, className,yearofcls,sem,deapart,Mobileno,datebirth,addr,bgroup,genderr};
        model.addRow(row);
        
    }
    if(!hasResult){
            JOptionPane.showMessageDialog(this, "No Any Students Of MSC I");
            
        }

    con.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
        
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here
                try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/collage", "root", "system");

    String sql = "SELECT * FROM student WHERE Class='MSC' AND yearofclass=2";
    PreparedStatement pstmt = con.prepareStatement(sql);
    ResultSet rs = pstmt.executeQuery();

    DefaultTableModel model = (DefaultTableModel) Table.getModel();
    model.setRowCount(0);  // Clear existing rows
    boolean hasResult=false;
    

    while (rs.next()) {
        hasResult =true;
        String studentRollnumber = String.valueOf(rs.getInt("Rollnumber"));
        String studentName = rs.getString("StudentName");
        String className = rs.getString("Class");
        String yearofcls=rs.getString("yearofclass");
        String sem=rs.getString("semester");
        String deapart=rs.getString("department");
        String Mobileno=rs.getString("mobile_no");
        String datebirth=rs.getString("date_of_birth");
        String addr=rs.getString("address");
        String bgroup=rs.getString("blood_group");
        String genderr=rs.getString("gender");

        String[] row = {studentRollnumber, studentName, className,yearofcls,sem,deapart,Mobileno,datebirth,addr,bgroup,genderr};
        model.addRow(row);
        
    }
    if(!hasResult){
            JOptionPane.showMessageDialog(this, "No Any Students Of MSC II");
            
        }

    con.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
        
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
                try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/collage", "root", "system");

    String sql = "SELECT * FROM student WHERE Class='MSC' AND yearofclass=3";
    PreparedStatement pstmt = con.prepareStatement(sql);
    ResultSet rs = pstmt.executeQuery();

    DefaultTableModel model = (DefaultTableModel) Table.getModel();
    model.setRowCount(0);  // Clear existing rows
    boolean hasResult=false;
    

    while (rs.next()) {
        hasResult =true;
        String studentRollnumber = String.valueOf(rs.getInt("Rollnumber"));
        String studentName = rs.getString("StudentName");
        String className = rs.getString("Class");
        String yearofcls=rs.getString("yearofclass");
        String sem=rs.getString("semester");
        String deapart=rs.getString("department");
        String Mobileno=rs.getString("mobile_no");
        String datebirth=rs.getString("date_of_birth");
        String addr=rs.getString("address");
        String bgroup=rs.getString("blood_group");
        String genderr=rs.getString("gender");

        String[] row = {studentRollnumber, studentName, className,yearofcls,sem,deapart,Mobileno,datebirth,addr,bgroup,genderr};
        model.addRow(row);
        
    }
    if(!hasResult){
            JOptionPane.showMessageDialog(this, "No Any Students Of MSC III");
            
        }

    con.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
        
    }//GEN-LAST:event_jButton18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Cource().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
